# code: language=yaml
site_name: IaC Demo - Fachschaft Informatik Uni Duisburg-Essen
site_description: Small exercises for demoing Infrastructure as Code with Ansible and Automation Controller
copyright: Copyright &copy; Computacenter 2025
edit_uri: ""
extra_css:
  - assets/stylesheets/tables.css
extra_javascript:
  - assets/javascripts/extra/refresh-on-toggle-dark-light.js
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path:
        - .
        - docs/ansible/snippets
        - docs/automation-platform/snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - toc:
      title: On this page
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
      lang: en
      separator: '[\s]'
  - git-revision-date-localized:
    # This plugin needs a Git executable and the .git folder
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]
      fallback_to_build_date: true
      locale: en
  - macros
  - privacy
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    admonition:
      example: octicons/terminal-24
  logo: assets/images/computacenter-logo-white.png
  language: de
  favicon: assets/images/computacenter-logo.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/TimGrt/IaC-Workshop-Uni-DuE
repo_name: TimGrt/IaC-Workshop-Uni-DuE
# Variables for Macros plugin, uncomment and add values if necessary
# extra:
#   workshop_url: https://catalog.partner.demo.redhat.com/workshop/7gswve
#   workshop_password: d3m0p4$$w0rd!
# Navigation definition
nav:
  - index.md
  - "Teil 1:<br>Vorbereitung": part1.md
  - "Teil 2:<br>Automatisierung": part2.md
  - "Teil 3:<br>Recap": part3.md
